services:
  postgres:
    container_name: postgres-sql-gp
    image: postgres
    environment:
      POSTGRES_USER: mouaad
      POSTGRES_PASSWORD: mouaad
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: gestion-personnel
    volumes:  # La section volumes doit être ici
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-gp
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
