spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gestion-personnel
    username: mouaad
    password: mouaad
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  mail:
    host: localhost
    port: 1025
    username: mouaad
    password: mouaad
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      expiration: 1800000  # expiration du JWT en millisecondes (30 minutes)
  mailing:
    frontend:
      activation-url: "http://localhost:4200/activate-account"

server:
  port: 8088